Controllers/LeaveRequestController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using AutoMapper;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using PMS.Data;
using PMS.Models;
using PMS.Services;
using PMS.Settings;

namespace PMS.Contracts
{
    [Authorize]
    public class LeaveRequestController : Controller
    {
        private readonly ILeaveTypeRepository _leaverepo;
        private readonly ILeaveAllocationRepository _leaveallocationrepo;
        private readonly ILeaveRequestRepository _leaverequestrepo;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;
        private readonly IMailService mailService;
        private readonly MailSettings _mailSettings;

        public LeaveRequestController(
            ILeaveTypeRepository leaverepo,
            ILeaveAllocationRepository leaveallocationrepo,
            ILeaveRequestRepository leaverequestrepo,
            IMapper mapper,
            IMailService mailService,
            UserManager<Employee> userManager,
            IOptions<MailSettings> mailSettings
            )
        {
            _leaverepo = leaverepo;
            _leaveallocationrepo = leaveallocationrepo;
            _leaverequestrepo = leaverequestrepo;
            _mapper = mapper;
            _userManager = userManager;
            //mailService = mailService;
            this.mailService = mailService;
            _mailSettings = mailSettings.Value;
        }
        [Authorize(Roles ="Administrator")]
        // GET: LeaveRequestController
        public async Task<ActionResult> Index()
        {
            var leaverequest = await _leaverequestrepo.FindAll();
            var leaveRequestModel = _mapper.Map<List<LeaveRequestViewModel>>(leaverequest);
            var model = new AdminLeaveRequestViewModel
            {
                TotalRequest= leaveRequestModel.Count,
                ApprovedRequest=leaveRequestModel.Count(q => q.Approved==true),
                PendingRequest = leaveRequestModel.Count(q => q.Approved==null),
                RejectedRequest = leaveRequestModel.Count(q => q.Approved==false),
                LeaveRequests = leaveRequestModel

            };
            return View(model);
        }

        public async Task<ActionResult> MyLeave()
        {
            var employee = await _userManager.GetUserAsync(User);
            var employeeid = employee.Id;
            var allocation = await _leaveallocationrepo.GetLeaveAllocationsByEmployee(employeeid);
            var employeeRequests = await _leaverequestrepo.GetLeaveRequestByEmployee(employeeid);

            var allocationModel = _mapper.Map<List<LeaveAllocationViewModel>>(allocation);
            var employeeRequestModel = _mapper.Map<List<LeaveRequestViewModel>>(employeeRequests);

            var model = new EmployeeLeaveRequestViewModel
            {
                LeaveAllocations = allocationModel,
                LeaveRequests = employeeRequestModel

            };
            return View(model);
        }

        // GET: LeaveRequestController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var leaverequest = await _leaverequestrepo.FindByID(id);
            var model = _mapper.Map<LeaveRequestViewModel>(leaverequest);
            return View(model);
        }

        public async Task<ActionResult> ApproveRequest(int id)
        {
            try
            {
                var userLoggedIn = await _userManager.GetUserAsync(User);
                var leaverequest = await _leaverequestrepo.FindByID(id);
                leaverequest.Approved = true;
                leaverequest.ApprovedById = userLoggedIn.Id;
                leaverequest.DateActioned = DateTime.Now;
                int DaysRequested = (int)(leaverequest.EndDate - leaverequest.StartDate).TotalDays;

                var employeeid = leaverequest.RequestingEmployeeId;
                var leavetypeid = leaverequest.LeaveTypeId;
                var allocation = await _leaveallocationrepo.GetLeaveAllocationsByEmployeeAndType(employeeid, leavetypeid);
                allocation.NumberOfDays = allocation.NumberOfDays - DaysRequested;


                await _leaverequestrepo.Update(leaverequest);
                await _leaveallocationrepo.Update(allocation);

                    return RedirectToAction(nameof(Index));
               
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index));
            }       
        }


        public async Task<ActionResult> RejectRequest(int id)
        {

            try
            {
                var userLoggedIn = await _userManager.GetUserAsync(User);
                var leaverequest = await _leaverequestrepo.FindByID(id);
                leaverequest.Approved = false;
                leaverequest.ApprovedById = userLoggedIn.Id;
                leaverequest.DateActioned = DateTime.Now;

                await _leaverequestrepo.Update(leaverequest);
              
                return RedirectToAction(nameof(Index));
               
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index));
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> DownloadFile()
        {
            var employee = await _userManager.GetUserAsync(User);
            var employeeid = employee.Id;
            var allocation = await _leaveallocationrepo.GetLeaveAllocationsByEmployee(employeeid.ToString());
            var employeeRequests = await _leaverequestrepo.GetLeaveRequestByEmployee(employeeid.ToString());

            var allocationModel = _mapper.Map<List<LeaveAllocationViewModel>>(allocation);
           var employeeRequestModel = _mapper.Map<List<LeaveRequestViewModel>>(employeeRequests);

            var model = new DownloadEmployeeLeaveRequestViewModel
            {
                LeaveAllocations = allocationModel,
                LeaveRequests = employeeRequestModel

            };

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Leave Request");
                var currentRow = 1;
                
                #region Headering
                worksheet.Cell(currentRow, 1).Value = "Hello ";
                worksheet.Cell(currentRow+1, 2).Value = "Sweet P";
                worksheet.Cell(currentRow+2, 3).Value = "Smiles Girl";
                #endregion Headering

                #region Header
                worksheet.Cell(currentRow+3, 1).Value = "First Name";
                worksheet.Cell(currentRow+3, 2).Value = "Last Name";
                worksheet.Cell(currentRow+3, 3).Value = "Start Date";
                worksheet.Cell(currentRow+3, 4).Value = "Start Date";
                #endregion Header

                #region Body
                foreach (var leave in model.LeaveRequests)
                {
                    currentRow++;
                    worksheet.Cell(currentRow + 4, 1).Value = leave.Employee.Firstname;
                    worksheet.Cell(currentRow + 4, 2).Value = leave.Employee.Lastname;
                    worksheet.Cell(currentRow + 4, 3).Value = leave.StartDate;
                    worksheet.Cell(currentRow + 4, 4).Value = leave.LeaveType.Name;

                }
                #endregion Body

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "LeaveRequests.xlsx"
                        );

                }
            }
        }

        // GET: LeaveRequestController/Create
        public async Task<ActionResult> Create()
        {
            var leavetypes = await _leaverepo.FindAll();
            var LeaveTypeItems = leavetypes.Select(q => new SelectListItem
            {
                Text=q.Name,
                Value= q.Id.ToString()

            });
            var model = new CreateLeaveRequestViewModel
            {
                LeaveTypes = LeaveTypeItems
            };
            return View(model);
        }

        // POST: LeaveRequestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveRequestViewModel model)
        {
            
            try
            {
                var startDate = Convert.ToDateTime(model.StartDate);
                var endDate = Convert.ToDateTime(model.EndDate);

                //load dropdown 
                var leavetypes = await _leaverepo.FindAll();
                var LeaveTypeItems = leavetypes.Select(q => new SelectListItem
                {
                    Text = q.Name,
                    Value = q.Id.ToString()

                });
                model.LeaveTypes = LeaveTypeItems;

                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                //compare dates
                if(DateTime.Compare(startDate, endDate) > 1 )
                {
                    ModelState.AddModelError("", "Start date cannot be further in the future than End date");
                    return View(model);
                }

                //current user
                var employee = await _userManager.GetUserAsync(User);

Controllers/LeaveTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PMS.Contracts;
using PMS.Data;
using PMS.Models;

namespace PMS.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LeaveTypesController : Controller
    {
        private readonly ILeaveTypeRepository _repo;
        private readonly IMapper _mapper;

        public LeaveTypesController(ILeaveTypeRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }

        // GET: LeaveTypes
        public async Task<ActionResult> Index()
        {
            var leavetypes = await _repo.FindAll();
            var model = _mapper.Map<List<LeaveType>, List<LeaveTypeViewModel>>(leavetypes.ToList());
            return View(model);           

            //var leavetypes = _repo.FindAll().ToList();
            //var model = _mapper.Map<List<LeaveType>, List<LeaveTypeViewModel>>(leavetypes);
            //return View(model);

        }

        // GET: LeaveTypes/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var isExists = await _repo.isExists(id);
            if(!isExists)
            {
                return NotFound();
            }

            var leavetype = await _repo.FindByID(id);
            var model = _mapper.Map<LeaveTypeViewModel>(leavetype);

            return View(model);
        }

        // GET: LeaveTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LeaveTypeViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View (model);
                   
                }
                var leaveType = _mapper.Map<LeaveType>(model);
                leaveType.DateCreated = DateTime.Now;

                var isSuccess =await _repo.Create(leaveType);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }
                var id = leaveType.Id;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: LeaveTypes/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var isExist = await _repo.isExists(id);
            if (!isExist)
            {
                return NotFound();
            }

            var leaveType = await _repo.FindByID(id);
            var model = _mapper.Map<LeaveTypeViewModel>(leaveType);
            return View(model);

        }

        // POST: LeaveTypes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LeaveTypeViewModel model)
        {
            try
            {
                // TODO: Add update logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var leaveType = _mapper.Map<LeaveType>(model);

                var isSuccess = await _repo.Update(leaveType);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: LeaveTypes/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            //if (!_repo.isExists(id))
            //{
            //    return NotFound();
            //}

            //var leaveType = _repo.FindByID(id);
            //var model = _mapper.Map<LeaveTypeViewModel>(leaveType);
            //return View(model);

           
                // TODO: Add delete logic here
                var leavetype = await _repo.FindByID(id);
                if (leavetype == null)
                {
                    return NotFound();
                }
                var isSuccess = await _repo.Delete(leavetype);

                if (!isSuccess)
                {
                   // ModelState.AddModelError("", "Something went wrong...");
                    return BadRequest();
                }

                return RedirectToAction(nameof(Index));
            
        }

    

        // POST: LeaveTypes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, LeaveTypeViewModel model)
        {
            try
            {
                // TODO: Add delete logic here
                var leavetype = await _repo.FindByID(id);
                if (leavetype==null)
                {
                    return NotFound();
                }
                var isSuccess = await _repo.Delete(leavetype);

                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PMS.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LeaveRequest" asp-action="Create">Apply for leave</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LeaveRequest" asp-action="MyLeave">My leave</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator"))
                            {


                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="LeaveTypes" asp-action="Index">Leave type</a>
                                        <a class="dropdown-item" asp-controller="LeaveAllocation" asp-action="Index">Leave allocaion</a>
                                        <a class="dropdown-item" asp-controller="LeaveRequest" asp-action="Index">Leave Request</a>
                                        <a class="dropdown-item" asp-controller="LeaveAllocation" asp-action="ListEmployees">Employees</a>
                                    </div>
                                </li>
                            }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - PMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
@using Microsoft.AspNetCore.Identity
@using PMS.Data;
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>@ViewData["Title"] - PMS</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    @*<link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />*@
    <link rel="stylesheet" href="~/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    @*<div class="hold-transition">
        <div class="wrapper">
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
    *@
    <div class="content">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>




    <!-- Main Footer -->
    <footer class="border-top footer text-muted">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Styled by <a href="https://adminlte.io">AdminLTE.io</a>
        </div>
        <!-- Default to the left -->
        <strong> Copyright &copy; @DateTime.Now.Year - Project Management System </strong> All rights reserved.
    </footer>


    @*


        </div>

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Styled by <a href="https://adminlte.io">AdminLTE.io</a>
            </div>
            <!-- Default to the left -->
            <strong> Copyright &copy; @DateTime.Now.Year - Project Management System </strong> All rights reserved.
        </footer>
        </div>

    *@
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>

    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    @*<script src="https://code.jquery.com.ui/1.12.1/jquery-ui.js"></script>*@
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @*</div>*@
</body>
</html>