Controllers/LeaveRequestController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using AutoMapper;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using PMS.Data;
using PMS.Models;
using PMS.Services;
using PMS.Settings;

namespace PMS.Contracts
{
    [Authorize]
    public class LeaveRequestController : Controller
    {
        private readonly ILeaveTypeRepository _leaverepo;
        private readonly ILeaveAllocationRepository _leaveallocationrepo;
        private readonly ILeaveRequestRepository _leaverequestrepo;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;
        private readonly IMailService mailService;
        private readonly MailSettings _mailSettings;

        public LeaveRequestController(
            ILeaveTypeRepository leaverepo,
            ILeaveAllocationRepository leaveallocationrepo,
            ILeaveRequestRepository leaverequestrepo,
            IMapper mapper,
            IMailService mailService,
            UserManager<Employee> userManager,
            IOptions<MailSettings> mailSettings
            )
        {
            _leaverepo = leaverepo;
            _leaveallocationrepo = leaveallocationrepo;
            _leaverequestrepo = leaverequestrepo;
            _mapper = mapper;
            _userManager = userManager;
            //mailService = mailService;
            this.mailService = mailService;
            _mailSettings = mailSettings.Value;
        }
        [Authorize(Roles ="Administrator")]
        // GET: LeaveRequestController
        public async Task<ActionResult> Index()
        {
            var leaverequest = await _leaverequestrepo.FindAll();
            var leaveRequestModel = _mapper.Map<List<LeaveRequestViewModel>>(leaverequest);
            var model = new AdminLeaveRequestViewModel
            {
                TotalRequest= leaveRequestModel.Count,
                ApprovedRequest=leaveRequestModel.Count(q => q.Approved==true),
                PendingRequest = leaveRequestModel.Count(q => q.Approved==null),
                RejectedRequest = leaveRequestModel.Count(q => q.Approved==false),
                LeaveRequests = leaveRequestModel

            };
            return View(model);
        }

        public async Task<ActionResult> MyLeave()
        {
            var employee = await _userManager.GetUserAsync(User);
            var employeeid = employee.Id;
            var allocation = await _leaveallocationrepo.GetLeaveAllocationsByEmployee(employeeid);
            var employeeRequests = await _leaverequestrepo.GetLeaveRequestByEmployee(employeeid);

            var allocationModel = _mapper.Map<List<LeaveAllocationViewModel>>(allocation);
            var employeeRequestModel = _mapper.Map<List<LeaveRequestViewModel>>(employeeRequests);

            var model = new EmployeeLeaveRequestViewModel
            {
                LeaveAllocations = allocationModel,
                LeaveRequests = employeeRequestModel

            };
            return View(model);
        }

        // GET: LeaveRequestController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var leaverequest = await _leaverequestrepo.FindByID(id);
            var model = _mapper.Map<LeaveRequestViewModel>(leaverequest);
            return View(model);
        }

        public async Task<ActionResult> ApproveRequest(int id)
        {
            try
            {
                var userLoggedIn = await _userManager.GetUserAsync(User);
                var leaverequest = await _leaverequestrepo.FindByID(id);
                leaverequest.Approved = true;
                leaverequest.ApprovedById = userLoggedIn.Id;
                leaverequest.DateActioned = DateTime.Now;
                int DaysRequested = (int)(leaverequest.EndDate - leaverequest.StartDate).TotalDays;

                var employeeid = leaverequest.RequestingEmployeeId;
                var leavetypeid = leaverequest.LeaveTypeId;
                var allocation = await _leaveallocationrepo.GetLeaveAllocationsByEmployeeAndType(employeeid, leavetypeid);
                allocation.NumberOfDays = allocation.NumberOfDays - DaysRequested;


                await _leaverequestrepo.Update(leaverequest);
                await _leaveallocationrepo.Update(allocation);

                    return RedirectToAction(nameof(Index));
               
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index));
            }       
        }


        public async Task<ActionResult> RejectRequest(int id)
        {

            try
            {
                var userLoggedIn = await _userManager.GetUserAsync(User);
                var leaverequest = await _leaverequestrepo.FindByID(id);
                leaverequest.Approved = false;
                leaverequest.ApprovedById = userLoggedIn.Id;
                leaverequest.DateActioned = DateTime.Now;

                await _leaverequestrepo.Update(leaverequest);
              
                return RedirectToAction(nameof(Index));
               
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index));
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> DownloadFile()
        {
            var employee = await _userManager.GetUserAsync(User);
            var employeeid = employee.Id;
            var allocation = await _leaveallocationrepo.GetLeaveAllocationsByEmployee(employeeid.ToString());
            var employeeRequests = await _leaverequestrepo.GetLeaveRequestByEmployee(employeeid.ToString());

            var allocationModel = _mapper.Map<List<LeaveAllocationViewModel>>(allocation);
           var employeeRequestModel = _mapper.Map<List<LeaveRequestViewModel>>(employeeRequests);

            var model = new DownloadEmployeeLeaveRequestViewModel
            {
                LeaveAllocations = allocationModel,
                LeaveRequests = employeeRequestModel

            };

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Leave Request");
                var currentRow = 1;
                
                #region Headering
                worksheet.Cell(currentRow, 1).Value = "Hello ";
                worksheet.Cell(currentRow+1, 2).Value = "Sweet P";
                worksheet.Cell(currentRow+2, 3).Value = "Smiles Girl";
                #endregion Headering

                #region Header
                worksheet.Cell(currentRow+3, 1).Value = "First Name";
                worksheet.Cell(currentRow+3, 2).Value = "Last Name";
                worksheet.Cell(currentRow+3, 3).Value = "Start Date";
                worksheet.Cell(currentRow+3, 4).Value = "Start Date";
                #endregion Header

                #region Body
                foreach (var leave in model.LeaveRequests)
                {
                    currentRow++;
                    worksheet.Cell(currentRow + 4, 1).Value = leave.Employee.Firstname;
                    worksheet.Cell(currentRow + 4, 2).Value = leave.Employee.Lastname;
                    worksheet.Cell(currentRow + 4, 3).Value = leave.StartDate;
                    worksheet.Cell(currentRow + 4, 4).Value = leave.LeaveType.Name;

                }
                #endregion Body

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "LeaveRequests.xlsx"
                        );

                }
            }
        }

        // GET: LeaveRequestController/Create
        public async Task<ActionResult> Create()
        {
            var leavetypes = await _leaverepo.FindAll();
            var LeaveTypeItems = leavetypes.Select(q => new SelectListItem
            {
                Text=q.Name,
                Value= q.Id.ToString()

            });
            var model = new CreateLeaveRequestViewModel
            {
                LeaveTypes = LeaveTypeItems
            };
            return View(model);
        }

        // POST: LeaveRequestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveRequestViewModel model)
        {
            
            try
            {
                var startDate = Convert.ToDateTime(model.StartDate);
                var endDate = Convert.ToDateTime(model.EndDate);

                //load dropdown 
                var leavetypes = await _leaverepo.FindAll();
                var LeaveTypeItems = leavetypes.Select(q => new SelectListItem
                {
                    Text = q.Name,
                    Value = q.Id.ToString()

                });
                model.LeaveTypes = LeaveTypeItems;

                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                //compare dates
                if(DateTime.Compare(startDate, endDate) > 1 )
                {
                    ModelState.AddModelError("", "Start date cannot be further in the future than End date");
                    return View(model);
                }

                //current user
                var employee = await _userManager.GetUserAsync(User);

Controllers/UploadsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PMS.Contracts;
using PMS.Data;
using PMS.Models;

namespace PMS.Controllers
{
    public class UploadsController : Controller
    {
        private readonly ILeaveTypeRepository _leaverepo;
        private readonly IFileModelRepository _fileuploadrepo;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;
        // GET: UploadsController

        public UploadsController(
            ILeaveTypeRepository leaverepo,
            IFileModelRepository fileuploadrepo,
            IMapper mapper,
            UserManager<Employee> userManager)
        {
            _leaverepo = leaverepo;
            _fileuploadrepo = fileuploadrepo;
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task<ActionResult> IndexAsync()
        {
            var files = await _fileuploadrepo.FindAll();
            //var types = await _leaverepo.FindAll();
            var filedmodel = _mapper.Map<List<FileModel>, List<FileModelViewModel>>(files.ToList());
           // var typedmodel = _mapper.Map<List<LeaveType>, List<LeaveTypeViewModel>>(types.ToList());

            var leavetypes = await _leaverepo.FindAll();
            var LeaveTypeItems = leavetypes.Select(q => new SelectListItem
            {
                Text = q.Name,
                Value = q.Id.ToString()

            });

            var model = new FileUploadViewModel
            {
                FilesOnFileSystem = filedmodel,
                LeaveTypes= LeaveTypeItems

            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UploadToFileSystem(List<IFormFile> files, string description, FileUploadViewModel model)
        //public async Task<IActionResult> UploadToFileSystem(List<IFormFile> files, string description)
        {
            foreach (var file in files)
            {
                var basePath = Path.Combine(Directory.GetCurrentDirectory() + "\\Files\\");
                bool basePathExists = System.IO.Directory.Exists(basePath);
                if (!basePathExists) Directory.CreateDirectory(basePath);
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var filePath = Path.Combine(basePath, file.FileName);
                var extension = Path.GetExtension(file.FileName);
                if (!System.IO.File.Exists(filePath))
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    var fileModel = new FileModelViewModel
                    {
                        CreatedOn = DateTime.UtcNow,
                        FileType = file.ContentType,
                        Extension = extension,
                        Name = fileName,
                        Description = description,
                        FilePath = filePath,
                        LeaveTypeId=model.LeaveTypeId
                    };

                    var fileupload = _mapper.Map<FileModel>(fileModel);
                    var isSuccess = await _fileuploadrepo.Create(fileupload);
                    if (!isSuccess)
                    {
                        ModelState.AddModelError("", "Something went wrong");
                        return RedirectToAction(nameof(Index));
                    }

                    // context.FilesOnFileSystem.Add(fileModel);
                    // context.SaveChanges();
                }
            }

            TempData["Message"] = "File successfully uploaded to File System.";
            return RedirectToAction("Index");
        }


        //public async Task<IActionResult> DownloadFileFromFileSystem(int id)
        //{

        //    var file = await context.FilesOnFileSystem.Where(x => x.Id == id).FirstOrDefaultAsync();
        //    if (file == null) return null;
        //    var memory = new MemoryStream();
        //    using (var stream = new FileStream(file.FilePath, FileMode.Open))
        //    {
        //        await stream.CopyToAsync(memory);
        //    }
        //    memory.Position = 0;
        //    return File(memory, file.FileType, file.Name + file.Extension);
        //}


        // GET: UploadsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UploadsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UploadsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }

        // GET: UploadsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UploadsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }

        // GET: UploadsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UploadsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/LeaveRequest/Create.cshtml
@model PMS.Models.CreateLeaveRequestViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>CreateLeaveRequestViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LeaveTypeId" class="control-label"></label>
                @Html.DropDownListFor(q => q.LeaveTypeId, new SelectList(Model.LeaveTypes, "Value", "Text"), "Select Leave Type", new { @class = "form-control" })

                <span asp-validation-for="LeaveTypeId" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control datepicker" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control datepicker" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label asp-for="RequestComment" class="control-label"></label>
                <textarea asp-for="RequestComment" class="form-control"></textarea>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    <script>
          $( function() {
              //$(".datepicker").datepicker({
              //    dateFormat: "yy-mm-dd"
              //    );
              $(".datepicker").datepicker();
          } );
    </script>
}

Views/LeaveRequest/Details.cshtml
@model PMS.Models.LeaveRequestViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Request for @Model.Employee.Lastname, @Model.Employee.Firstname</h4>
    <hr />

    @if (Model.Approved == null)
    {
        <div class="alert alert-warning" role="alert">
            <h4 class="alert-heading">Pending Approval!</h4>
            <p>
                <strong> @Html.DisplayNameFor(model => model.RequestingEmployeeId) :</strong>
                @Model.Employee.Lastname, @Model.Employee.Lastname,
                @Model.Employee.Lastname, @Model.Employee.Firstname
            </p>
            <hr>
            <p class="mb-0">
                @Html.DisplayFor(model => model.StartDate) -
                @Html.DisplayFor(model => model.EndDate)
            </p>
        </div>
    }
    @if (Model.Approved == true)
    {
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Approval by @Model.ApprovedBy.Lastname,  @Model.ApprovedBy.Firstname </h4>
            <p>
                <strong> @Html.DisplayNameFor(model => model.RequestingEmployeeId) :</strong>
                @Model.Employee.Lastname, @Model.Employee.Lastname,
            </p>
            <hr>
            <p class="mb-0">
                @Html.DisplayFor(model => model.StartDate) -
                @Html.DisplayFor(model => model.EndDate)
            </p>
        </div>
    }
    @if (Model.Approved == false)
    {
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Rejected by @Model.ApprovedBy.Lastname,  @Model.ApprovedBy.Firstname </h4>
            <p>
                <strong>Employee:</strong>
                @Model.Employee.Lastname, @Model.Employee.Lastname,
            </p>
            <hr>
            <p class="mb-0">
                @Html.DisplayFor(model => model.StartDate) -
                @Html.DisplayFor(model => model.EndDate)
            </p>
        </div>
    }
<dl class="row">

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.RequestingEmployeeId)
    </dt>
    <dd class="col-sm-10">
        @Model.Employee.Lastname, @Model.Employee.Lastname,
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.StartDate)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.StartDate)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.EndDate)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.EndDate)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.LeaveType.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.LeaveType.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.DateRequested)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.DateRequested)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.RequestComment)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.RequestComment)
    </dd>

</dl>
</div>
<div>
    @if (Model.Approved == null)
    {
        <a class="btn btn-success" asp-action="ApproveRequest" asp-route-id="@Model.Id">
            <i class="fa fa-tick"></i> Approve
        </a>

        <a class="btn btn-danger" asp-action="RejectRequest" asp-route-id="@Model.Id">
            <i class="fa fa-remove"></i> Reject
        </a>
    }



    <a class="btn btn-outline-primary" asp-action="Index">
        <i class="fa fa-arrow-left"></i> Back to list
    </a>

    @*<a asp-action="Index">Back to List</a>*@
</div>

Views/LeaveRequest/Index.cshtml
@model AdminLeaveRequestViewModel

@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="row">
    <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body text-center">
                <h1 class="card-title">@Model.TotalRequest</h1>
                <h5 class="card-text">@Html.DisplayNameFor(model => model.TotalRequest)</h5>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body text-center">
                <h1 class="card-title text-success">@Model.ApprovedRequest</h1>
                <h5 class="card-text">@Html.DisplayNameFor(model => model.ApprovedRequest)</h5>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body text-center">
                <h1 class="card-title text-warning">@Model.PendingRequest</h1>
                <h5 class="card-text">@Html.DisplayNameFor(model => model.PendingRequest)</h5>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body text-center">
                <h1 class="card-title text-danger">@Model.RejectedRequest</h1>
                <h5 class="card-text">@Html.DisplayNameFor(model => model.RejectedRequest)</h5>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<div class="row">
    <div class="col-md-3">
        <div class="info-box">
            <Span class="info-box bg-info"> <i class="fa fa-envelope"></i>  </Span>

            <div class="info-box-content">
                <span class="info-box-text">@Model.TotalRequest</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.TotalRequest)</span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box bg-success"> <i class="fa fa-check-circle"></i>       </span>

            <div class="info-box-content">
                <span class="info-box-text">@Model.ApprovedRequest</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.ApprovedRequest)</span>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box bg-warning"> <i class="fa fa-exclamation"></i>       </span>

            <div class="info-box-content">
                <span class="info-box-text">@Model.PendingRequest</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.PendingRequest)</span>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box bg-danger">  <i class="fa fa-envelope"></i>      </span>

            <div class="info-box-content">
                <span class="info-box-text">@Model.RejectedRequest</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.RejectedRequest)</span>
            </div>
        </div>
    </div>
</div>



<br />
<br />
<table id="tblData" class="table">
    <thead>
        <tr>

            <th>
                Employee Name
            </th>
            <th>
                StartnDate
            </th>
            <th>
                End Date
            </th>
            <th>
                Leave Type
            </th>
            <th>
                Date Requested
            </th>

            <th>
                Approval Status
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveRequests)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Employee.Firstname)
                    @Html.DisplayFor(modelItem => item.Employee.Lastname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateRequested)
                </td>

                <td>
                    @if (item.Approved == true)
                    {
                        <span class="badge badge-success">Approved</span>
                    }
                    else if (item.Approved == false)
                    {
                        <span class="badge badge-danger">Rejected</span>
                    }
                    else
                    {
                        <span class="badge badge-warning">Pending Approval</span>
                    }
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                    <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Id">
                        <i class="fa fa-file"></i> Review
                    </a>
                    @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }
    </tbody>
</table>
<br />


@section Scripts{
    <script>
        $(document).ready(function () {
            $('#tblData').DataTable();
        });

    </script>
}

Views/LeaveRequest/MyLeave.cshtml
@model EmployeeLeaveRequestViewModel

@{
    ViewData["Title"] = "MyLeave";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>MyLeave</h1>

<div class="jumbotron">
    <div class="card">
        <ul class="list-group list-group-flush">
            @foreach (var item in Model.LeaveAllocations)
            {
                <li class="list-group-item">
                    <h6>
                        @item.LeaveType.Name
                        <span class="badge badge-secondary">@item.NumberOfDays</span>
                    </h6>
                </li>
            }
        </ul>
    </div>
</div>

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@
<table id="tblData" class="table">
    <thead>
        <tr>
            <th>
                Leave Type
            </th>

            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>

            <th>
                Date Requested
            </th>

            <th>
                Approval status
            </th>
            <th>
                Cancel Request
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveRequests)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.DateRequested)
                </td>

                <td>
                    @if (item.Approved == true)
                    {
                        <span class="badge badge-success">Approved</span>
                    }
                    else if (item.Approved == false)
                    {
                        <span class="badge badge-danger">Rejected</span>
                    }
                    else
                    {
                        <span class="badge badge-warning">Pending Approval</span>
                    }
                </td>

                <td>
                    @if (item.StartDate > DateTime.Now || item.Approved == true)
                    {
                        <a asp-action="CancelRequest" asp-route-id="@item.Id" class="btn btn-danger"
                           onclick="return confirm('Are you sure you want to delete this record?')">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                            Cancel Request
                        </a>
                    }



                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }
    </tbody>
</table>

<br />
<h3>Download here</h3>

@*<form id="form1" action="LeaveRequest/DownloadFile" method="post">
        <a class="btn btn-outline-success" onclick="document.getElementById('form1').submit();">
            <i class="fa fa-download"></i> Review
        </a>
    </form>*@


@*<input type="submit" value="Create" class="btn btn-success btn-block" />*@


<form asp-controller="LeaveRequest"
      asp-action="DownloadFile" method="post">
    @Html.EditorForModel()
    <br />
    <input type="submit" name="Download" value="Down" class="btn btn-success btn-block" />


</form>

<br />

<a class="btn btn-outline-success" asp-controller="Uploads" asp-action="Index">
    <i class="fa fa-download"></i> File upload
</a>



@section Scripts{
    <script>
        $(document).ready(function () {
            $('#tblData').DataTable();
        });

    </script>
}